---
# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

APPLY_FIXES: disabled
# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling formats will be disabled by default
# ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
DISABLE:
  - CLOUDFORMATION
  - COPYPASTE # Uncomment to disable checks of excessive copy-pastes
  - CSS
  - EDITORCONFIG
  - SPELL # Uncomment to disable checks of spelling mistakes
  - JAVASCRIPT
  - TYPESCRIPT
  - TEKTON
DISABLE_LINTERS:
  - JSON_PRETTIER
  - REPOSITORY_KICS
  - SPELL_PROSELINT
  - SPELL_MISSPELL
  - SPELL_VALE
  - TYPESCRIPT_ES # These I cannot get to work, cannot find the client files at all (Default scanner needs to be looking in a different directory other then root)
  - TYPESCRIPT_STANDARD
  - TYPESCRIPT_PRETTIER
  - JAVASCRIPT_ES
  - JAVASCRIPT_PRETTIER
  - JAVASCRIPT_STANDARD
  - CSHARP_DOTNET_FORMAT # This isn't supporting .net 8 yet
  - REPOSITORY_DEVSKIM # There's a git ownership issue with this one : fatal: detected dubious ownership in repository at '/github/workspace/.git'
DISABLE_ERRORS_LINTERS:
  - PYTHON_BANDIT
  - PYTHON_PYRIGHT
  - REPOSITORY_DEVSKIM
  - REPOSITORY_GRYPE
  - REPOSITORY_SEMGREP
PRINT_ALL_FILES: false
JSON_JSONLINT_FILTER_REGEX_EXCLUDE: '(\.vscode/)'
BASH_FILTER_REGEX_EXCLUDE: "(lib)"
MARKDOWN_FILTER_REGEX_EXCLUDE: '(license\.md|docs/licenses)'
MARKDOWN_MARKDOWN_LINK_CHECK_DISABLE_ERRORS: true
SPELL_VALE_FILE_EXTENSIONS:
  - .md
SPELL_FILTER_REGEX_EXCLUDE: (valestyles|\.github|docs/licenses)
DOCKERFILE_HADOLINT_ARGUMENTS: "--ignore DL3003 --ignore DL3007 --ignore DL3013 --ignore DL3016 --ignore DL3018 --ignore DL3028 --ignore DL3059 --ignore DL4001 --ignore DL4006 --ignore SC2015 --ignore SC2016 --ignore SC2039 --ignore SC2086 --ignore SC1091 --ignore SC3046"
REPOSITORY_TRIVY_ARGUMENTS:
  - "--skip-dirs"
  - ".automation/test"
  - "--skip-dirs"
  - ".venv"
SHOW_ELAPSED_TIME: true
FLAVOR_SUGGESTIONS: false
EMAIL_REPORTER: false
FILEIO_REPORTER: false
JSON_REPORTER: true
SARIF_REPORTER: true
# The following actually does work, but it's throwing errors that I don't know how to resolve. 
# Local steps to resolve
# npm install ts-standard
# npx ts-standard
# TYPESCRIPT_STANDARD_ARGUMENTS: 
#  - "--project"
#  - "./expressedrealms.client/tsconfig.json"
