version: '3.4'

networks:
  expressed-realms-network:
    driver: bridge
    
services:
  myapp:
    container_name: expressed-realms-vue-app
    build:
      context: ./expressedrealms.client
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - ./expressedrealms.client:/usr/local/apps/myapp/dev
      - ignore:/usr/local/apps/myapp/dev/node_modules/
      - ${USERPROFILE}/.aspnet/https:/https
    networks:
      - expressed-realms-network
    depends_on:
      webapi:
        condition: service_started
  
  webapi:
    container_name: expressed-realms-web-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_HTTPS_PORTS=5001
      - ASPNETCORE_HTTP_PORTS=5000
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERTIFICATE_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/localhost.pfx
      - ConnectionStrings__DefaultConnection=Host=expressed-realms-db;Port=5432;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
    ports:
      - '5000:5000'
      - '5001:5001'
    volumes:
      - ${USERPROFILE}/.aspnet/https:/https:ro
    networks:
      - expressed-realms-network
    depends_on:
      postgres:
        condition: service_healthy
        
  postgres:
    container_name: expressed-realms-db
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - expressed-realms-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d expressedRealms"]
      interval: 2s
      timeout: 5s
      retries: 3

  cypress-e2e-firefox:
    image: "cypress/included"
    depends_on:
      - myapp
    environment:
      - CYPRESS_baseUrl=https://myapp:5173
    working_dir: /e2e
    volumes:
      - ./expressedrealms.client/:/e2e
    networks:
      - expressed-realms-network
    command: --browser firefox
        
  cypress-e2e-chrome:
    image: "cypress/included"
    depends_on:
      - myapp
    environment:
      - CYPRESS_baseUrl=https://myapp:5173
    working_dir: /e2e
    volumes:
      - ./expressedrealms.client/:/e2e
    networks:
      - expressed-realms-network
    command: --browser chrome
  
  cypress-component-chrome:
    image: "cypress/included"
    depends_on:
      - myapp
    environment:
      - CYPRESS_baseUrl=https://myapp:5173
    working_dir: /e2e
    volumes:
      - ./expressedrealms.client/:/e2e
    networks:
      - expressed-realms-network
    command: --component --browser chrome
    
  cypress-component-firefox:
    image: "cypress/included"
    depends_on:
      - myapp
    environment:
      - CYPRESS_baseUrl=https://myapp:5173
    working_dir: /e2e
    volumes:
      - ./expressedrealms.client/:/e2e
    networks:
      - expressed-realms-network
    command: --component --browser firefox


volumes:
  ignore:
  db_data:
  pgAdmin_data: