version: '3.4'

networks:
  expressed-realms-network:
    driver: bridge
    
services:
  
  cypress-component-chrome:
    image: "cypress/included"
    working_dir: /e2e
    volumes:
      - ./expressedrealms.client/:/e2e
    networks:
      - expressed-realms-network
    command: --component --browser chrome
    
  cypress-component-firefox:
    image: "cypress/included"
    working_dir: /e2e
    volumes:
      - ./expressedrealms.client/:/e2e
    networks:
      - expressed-realms-network
    command: --component --browser firefox


volumes:
  ignore:
  db_data:
  pgAdmin_data: