version: '3.4'

networks:
  expressed-realms-network:
    driver: bridge
    
services:
  myapp:
    container_name: expressed-realms-vue-app
    build:
      context: ./expressedrealms.client
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - ./expressedrealms.client:/usr/local/apps/myapp/dev
      - ignore:/usr/local/apps/myapp/dev/node_modules/
      - ${USERPROFILE}/.aspnet/https:/https
    networks:
      - expressed-realms-network
    #depends_on:
    #  webapi:
    #    condition: service_started
  
  cypress-component-chrome:
    image: "cypress/included"
    depends_on:
      - myapp
    environment:
      - CYPRESS_baseUrl=https://myapp:5173
    working_dir: /e2e
    volumes:
      - ./expressedrealms.client/:/e2e
    networks:
      - expressed-realms-network
    command: --component --browser chrome
    
  cypress-component-firefox:
    image: "cypress/included"
    depends_on:
      - myapp
    environment:
      - CYPRESS_baseUrl=https://myapp:5173
    working_dir: /e2e
    volumes:
      - ./expressedrealms.client/:/e2e
    networks:
      - expressed-realms-network
    command: --component --browser firefox


volumes:
  ignore:
  db_data:
  pgAdmin_data: