site_name: Expressed Realms
site_description: All in one tool for Society in Shadows

theme:
  name: material
  features:
    - navigation.instant
    - navigation.top
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-2
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences

repo_url: https://github.com/Society-In-Shadow/ExpressedRealms
repo_name: Expressed Realms

nav:
  - Setup / Architecture:
      - API Design: apiDesign.md
      - Architecture: architecture.md
      - Creating GPG Keys: creatingGPGKeys.md
      - Database: database.md
      - Docker / Podman: docker-podman.md
      - Fedora Setup: fedoraSetup.md
      - Github Access Tokens: githubAccessTokens.md
      - Migrations: migrations.md
      - PGAdmin Setup: pgadminSetup.md
      - Prospective Employers: prospectiveEmployers.md
      - Windows Setup: windowsSetup.md
      - Linux Setup: linuxSetupInstructions.md
  - Testing:
    - Backend Unit Testing: backendUnitTesting.md
    - Component Testing: componentTesting.md
    - Cypress: cypress.md
    - Vite Testing: vitesting.md
  - UI:
    - Tooltips: tooltips.md
    - Forms: forms.md
    - Dialogs: dialogs.md
  - Backend:
    - CMS Sections: cmsSections.md
    - Discord Support: discordSupport.md
    - Modifier System: modifierSystem.md
    - Permissions & Policies: permissionsAndPolicies.md
    - Repository Standards: repositoryStandards.md
    - Scriban: scriban.md
    - Use Cases: useCases.md
  - Database:
      - EF Core Practices: efCorePractices.md
